### ISSUE TITLE
Website addition: cool DEC-people's accomplishments 

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-ethics-club#187]
While DEC obviously can't take the credit for all the cool things that our members do, I think it would be cool to have a space on the website to celebrate DEC members ethics-related accomplishments because:
- More people might hear about them!
- People have told us that attending DEC has been helpful - and in the future we may need small amounts of money to continue operating, and it would be nice to have 
- I like to think about it when I feel sad

@HuwWDay send something out in the next email + also mention it in the next meeting and just say "if you've done something cool todo with DEC and you wanna share it with the community, let us know" @ninadicara to add it to the testimonial question!
Related to #225 

For example it might contain 1-3 sentences celebrating:
- Our paper (and potential future papers)
- Kamilla's [recent paper](https://ieeexplore.ieee.org/document/9932837/)
- Huw's outreach

## TODO
- [ ] ask each person for permission
- [ ] ask each person to approve the sentence or two
- [ ] think about how to credit these people
- [ ] advertise that people can tell us about this in the newsletter
