### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-ethics-club#41]
We want a gh-pages website for Data Ethics Club to make it more accessible.

We're going to try to use sphinx!

## To-dos
- [x] Create basic website
- [ ] Buy/add domain
- [x] Update README and link to website so as not to duplicate information
- [x] Update how-to-guide with updated workflows, including, e.g.:
  - [x] How to update website
  - [x] How to update next meeting link
  - [x] New GH repo directory structure
  - [x] Add all these to the website content under "Contribute"? And possible subcategory "Create your own Data Ethics Club"

## Ideas

Must-haves:
- A nice landing page
- Easy to find information on our next meeting
- All the information that is in the README.
- Navigate our discussion write-ups

Nice to haves:
- Embedded mailchimp sign-up
- Sortable/searchable table for reading list: could be possible using a Jupyter Notebook page of the website using something like [this itables package](https://github.com/mwouts/itables)
- Zotero badges automatically assigned to all of the meeting write-ups, like SORSE.
- A nicely displayed calendar, where people can see upcoming events and download them to their calendars: this could potentially be done automatically either:
    - Using something like [Open Research Calendar](https://openresearchcalendar.github.io/)'s approach, i.e. (using a GH Action to) run a script which extracts info from things in the meetings folder and adds them to a Google Calendar using the Google API - from there it should be [easy](https://gist.github.com/iani/8906741) to embed a google calendar. 
    - Or populating an .ics calendar using JavaScript (SORSE use [Full Calendar](https://fullcalendar.io/#demos)) from the markdown YAML, like the [SORSE calendar](https://github.com/SORSE/sorse.github.io/blob/master/_layouts/calendar.html) or [upcoming events](https://github.com/SORSE/sorse.github.io/blob/master/_includes/upcoming-events.html) (my fave option, which I think would work with sphinx)
    - Similarly, it would be cool to have a page which redirects to the information for the upcoming meeting. Ideally, we would have a GH pages action to automatically update to this when a new meeting is created, but perhaps to begin with, we can just manually add the link to the next meeting.
- (Future): Display the how-to-guide so that people can read that there.

**Comment by NatalieThurlby** [comment]
Thoughts: might change the write-ups bit to a general blog bit. That way it would be a bit more flexible for other uses, e.g. announcing papers, or survey results, etc.

I'm planning to change the meetings page so that the meetings are displayed using the [`toctree` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html) rather than in a markdown table. This would mean that you could navigate between them using the left navigation panel.

**Comment by ninadicara** [comment]
I like the ideas of write ups being blogs! 

Also wondering whether we should buy a name for the website? Would make it easier to send people to it - at the mo the easiest way is to click through from GitHub

**Comment by NatalieThurlby** [comment]
Sure I'll ask if we can buy it through JGI
