### ISSUE TITLE
Set Data Ethics Club back up for the next series of meetings!

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-ethics-club#69]
DEC 2.0 - lets go! I've tried to do a brain dump of all the things we need to do and link to new or existing issues where relevant so we can keep track.

Aiming to restart 14th July

## Organising tasks
- [x] Organise an organisers meeting to organise the upcoming series (@ninadicara @NatalieThurlby @HDiscoDay)
- [x] Set up a DEC HackMD account (#52) (@NatalieThurlby)
- [x] Set up a new recurring Zoom meeting link that has all of us as hosts (@ninadicara)
- [x] Finalise the write ups from the last couple of meetings on HackMD (#68) (@HDiscoDay to do one)
- [x] Update the MEETINGS.MD file with new meeting times (~~@ninadicara~~ @NatalieThurlby)
- [x] Decide on material for the first meeting back (@HDiscoDay)
- [x] Send out a survey for feedback? ( #74) (@NatalieThurlby)
- [x] Set up calendar invites (@NatalieThurlby)

## Repository maintenance tasks
- [x] Check all our contributors are up to date (#62, #38) 
- [x] Add any outstanding suggestions to the reading list (#64 #61)
- [x] Add a more obvious link to the reading list from the README (#60)

## Other
- [x] Website development (#41) (@NatalieThurlby)

**Comment by ninadicara** [comment]
First piece will be https://www.youtube.com/watch?v=lCjspXB5F4A

**Comment by NatalieThurlby** [comment]
Note: I'm just waiting to set up the first draft of the website to set up the calendar invites: hopefully by tomorrow

**Comment by NatalieThurlby** [comment]
@ninadicara: when you do the `MEETINGS.md`, just wanted to let you know where it has moved/renamed to. It is now in `site/contents/meetings/meetings.md`
